### ISSUE TITLE
بانک تجارت 

### ISSUE THREAD

**Issue by amireho3ein** [ali-zahedi/az-iranian-bank-gateways#1]
برای بانک تجارت  این پکیج کار نمی کنه ؟
ممنون میشم در این مورد راهنمایم کنید.

**Comment by ali-zahedi** [comment]
سلام وقت بخیر. 
حتما. 
من به درگاه بانک تجارت دسترسی نداشتم اگر بتونید کمک کنید و زحمت چک کردن رو در پروسه توسعه بکشید فکر می کنم بتونیم خیلی سریع درگاه رو راه اندازی بکنیم. 
برای هماهنگی با این ایمیل در ارتباط باشید

 ali.zahedigol@gmail.com
