### ISSUE TITLE
Vulnerability Report

### ISSUE THREAD

**Issue by alirezac0** [ali-zahedi/az-iranian-bank-gateways#131]
Hi there, recently, I found a security bug in this project. Do you mind enabling project [private-vulnerability-reporting-for-a-repository](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository#enabling-or-disabling-private-vulnerability-reporting-for-a-repository), so I can report the bug privately. After maintainers review and confirm the bug, I will submit a CVE request to https://cveform.mitre.org/ to get a CVE ID. When the bug is fixed, the report can be disclosed which will be referenced by CVE information parts.

سلام،

به تازگی یک باگ امنیتی در این پروژه پیدا کرده‌ام. آیا امکان فعال کردن گزارش‌دهی خصوصی آسیب‌پذیری برای این پروژه از طریق قابلیت مشاوره امنیتی گیت‌هاب وجود دارد؟ [لینک به اسناد گیت‌هاب در مورد گزارش‌دهی خصوصی](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository#enabling-or-disabling-private-vulnerability-reporting-for-a-repository)

با این کار می‌توانم جزئیات باگ را به صورت خصوصی به گزارش کنم تا بررسی و تأیید شود. پس از تأیید،یک شناسه (CVE) در https://cveform.mitre.org/ درخواست خواهم داد و آسیب پذیری مذکور با شناسه مورد نظر شناخته میشود.

**Comment by ali-zahedi** [comment]
سلام وقت بخیر و ممنون از مشارکت شما. 
فعال شد.
