### ISSUE TITLE
ست کردن در ری‌اکت

### ISSUE THREAD

**Issue by dv1167** [ali-zahedi/az-iranian-bank-gateways#17]
بعد از ست کردن یو‌آر‌ال‌ها و بقیه تنطیمات مربوطه در سمت سرور(جنگو) این کدهارو در سمت فرانت‌آند(ری‌اکت) نوشتم:
`<Button onClick={handleSubmit}>پرداخت</Button>`

`  const handleSubmit = ({ history }) => {
    axios
      .post("/go-to-gateway/")
      .then((response) => {
        console.log(response);
      })
      .catch((error) => {
        console.log(error);
      });
  };`
درواقع با استفاده از اکسیوس، میخام برم به پیچ آیدی‌پی که مبلغ هم با خودش ببره.
اما ارور ۴۰۳ میگیرم
البته باید هدر هم ست بشه و فرستاده بشه سمت بانک

**Comment by ali-zahedi** [comment]
سلام وقت بخیر .

چیزی شما لازم نیست روی هدر ست بکنید برای درگاه بانک.

لطفا کدهای `go-to-gateway` این قسمت رو به اشتراک بگذارید.  که بتونیم بررسی بکنیم با هم.

**Comment by ali-zahedi** [comment]
**نکته**:دقت کنید که کاربر رو باید با مرورگر به سمت درگاه بانک منتقل کنید

**Comment by dv1167** [comment]
سلام
من یه کد ساده رو پوش کردم روی ریپوزیتوری.
توی این کد، مبلغی از دیتابیس خونده میشه و با متد پست باید فرستاده بشه به درگاه بانک.
مشکل اول اینه که ارور ۴۰۳ میده
توی مرحله بعد حتی اگر go-to-gateway رو csrf_exempt کنیم این ارور رو میگیریم:
Cross-Origin Request Blocked: ... (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)
همچنین هدر هم بفرستیم جواب نمیده:
{ headers: { "Access-Control-Allow-Origin": "*" }}
این مراحلی بوده که من رفتم

**Comment by ali-zahedi** [comment]
تاکید دارم که کاربر رو باید با مرورگر به یو ار ال `/go-to-gateway/` هدایت کنید. 
و همچنین کد این متد رو اینجا قرار ندادید که بتونیم کمکی بهتون بکنیم.

**Comment by dv1167** [comment]
تا اونجاییکه من میدونستم همه ادرسها رو با مرورگر فرستادم
این لینک فایل ری‌اکت مربوز به آیدی پی هستش:
https://github.com/dv1167/MyRep/blob/4532fe2e0ca72f9e561b1471e68ae1215c32c372/frontend/src/components/IdPay.jsx
این هم لینک کل پروژه ساده شدست
https://github.com/dv1167/MyRep.git

**Comment by ali-zahedi** [comment]
@dv1167 همونطور که عرض کردم کاربر رو باید با مرورگر منتقل کنید. 

`redirect` 

چیزی که من میبینم شما در حال درخواست دادن هستید، نه انتقال کاربر. 

احتمال خیلی زیاد برای همین هست که مشکل دارید.

**Comment by ali-zahedi** [comment]
با توجه به اینکه فید بک دیگری نگرفتیم، فرض رو بر این میزاریم که مورد حل شده و من این ایشو رو میبندم.
 اگر مورد حل نشده بود حتما از طریق گذاشتن پیام همینجا میتونید دوباره ایشو رو باز کنید.
