### ISSUE TITLE
callback_url Error

### ISSUE THREAD

**Issue by MDswdq** [ali-zahedi/az-iranian-bank-gateways#18]
سلام وقت به خیر,  بنده در حال استفاده از این پکیج هستم که در هنگام برگشت از درگاه ( IDPay )  با ارور زیر مواجه میشم

AttributeError at /bankgateways/callback/
"NoneType" object has no attribute "callback_url"

داخل بخش ادمین تمامی status ها به حالت Redirect To Bank هستند
ورژون جنگو پروژه من = 3.2.5
ورژن azbankgateways = 1.6.11

نکته: تمامی کدهای برنامه‌ی من، حاصل کپی پیست کردن کد های قرار داده شده داخل صفحه ی این ماژول هست(و ترکیب با فیلم اموزشی) 

![Error](https://user-images.githubusercontent.com/72674353/128673197-a415ff11-087b-497f-8700-4bbc9c23d240.png)

**Comment by ali-zahedi** [comment]
سلام خیلی ممنون بابت اینکه این مورد رو مطرح کردید. 
لطفا بادی متدی که با اون کاربر رو به درگاه بانک هدایت می کنید رو هم اینجا قرار بدید.

**Comment by MDswdq** [comment]
def go_to_gateway_view(request):
    # خواندن مبلغ از هر جایی که مد نظر است
    amount = 50000
    # تنظیم شماره موبایل کاربر از هر جایی که مد نظر است
    user_mobile_number = '+989112221234'  # اختیاری

    factory = bankfactories.BankFactory()
    bank = factory.create()  # or factory.create(bank_models.BankType.BMI) or set identifier
    bank.set_request(request)
    bank.set_amount(amount)
    # یو آر ال بازگشت به نرم افزار برای ادامه فرآیند
    bank.set_client_callback_url("/callback-gateway/")
    bank.set_mobile_number(user_mobile_number)  # اختیاری

    # در صورت تمایل اتصال این رکورد به رکورد فاکتور یا هر چیزی که بعدا بتوانید ارتباط بین محصول یا خدمات را با این
    # پرداخت برقرار کنید.
    bank_record = bank.ready()

    # هدایت کاربر به درگاه بانک
    return bank.redirect_gateway()


def callback_gateway_view(request):
    tracking_code = request.GET.get(settings.TRACKING_CODE_QUERY_PARAM, None)
    if not tracking_code:
        logging.debug("این لینک معتبر نیست.")
        raise Http404

    try:
        bank_record = bank_models.Bank.objects.get(tracking_code=tracking_code)
    except bank_models.Bank.DoesNotExist:
        logging.debug("این لینک معتبر نیست.")
        raise Http404

    # در این قسمت باید از طریق داده هایی که در بانک رکورد وجود دارد، رکورد متناظر یا هر اقدام مقتضی دیگر را انجام دهیم
    if bank_record.is_success:
        # پرداخت با موفقیت انجام پذیرفته است و بانک تایید کرده است.
        # می توانید کاربر را به صفحه نتیجه هدایت کنید یا نتیجه را نمایش دهید.
        return HttpResponse("پرداخت با موفقیت انجام شد.")

    # پرداخت موفق نبوده است. اگر پول کم شده است ظرف مدت ۴۸ ساعت پول به حساب شما بازخواهد گشت.
    return HttpResponse(
        "پرداخت با شکست مواجه شده است. اگر پول کم شده است ظرف مدت ۴۸ ساعت پول به حساب شما بازخواهد گشت.")


کد ها دقیقا کپی شده و طبق آموزش پیش رفتم

**Comment by ali-zahedi** [comment]
علی رقم پیگیری 
این موضوع بنظر حل شده میاد. من این ایشو رو میبندم در صورتی که موردی در این رابطه بود حتما در رابطه با  مجدد باز کردن آن معطل نکنید.
