### ISSUE TITLE
Invalid format string

### ISSUE THREAD

**Issue by masiha972** [ali-zahedi/az-iranian-bank-gateways#19]
سلام خوبید؟
ببخشید مزاحم میشم من وقتی که از درگاه پرداخت بانک ملی استفاده میکنم این ارور را میدهد Invalid format string

response = get_response(request) 
 response = wrapped_callback(request, *callback_args, **callback_kwargs) 

bank_record = bank.ready() 
self.pay() 
data = self.get_pay_data()
time_now = datetime.datetime.now().strftime('%m/%d/%Y %H:%M:%S %P') 

مشکل چیست

ممنون

**Comment by masiha972** [comment]
سلام من این مشکل حل کردم ولی ئقتی که درخواست انجام میشو
 response code 1025  گوید اطلاعات SignData ارسالی اشتباه است
است ومی

**Comment by ali-zahedi** [comment]
سلام وقت بخیر. 

1. ورژن جنگو
2. ورژن azbank
3. کدهایی که باهاش به بانک متصل می شوید رو هم شیر کنید که بتونیم ببینیم چه اتفاقی میفته.

**Comment by masiha972** [comment]
جنگو ورژن 3.2.6
azbank ورژن 1.6.11

------------------------------------------------------

setting:
AZ_IRANIAN_BANK_GATEWAYS = {
   'GATEWAYS': {
       'BMI': {
           'MERCHANT_CODE': '000000140212149',
           'TERMINAL_CODE': '24000615',
           'SECRET_KEY': 'kLheA+FS7MLoLlLVESE3v3/FP07uLaRw',
       },
   },
   'DEFAULT': 'BMI',
   'CURRENCY': 'IRR', # اختیاری
   'TRACKING_CODE_QUERY_PARAM': 'tc', # اختیاری
   'TRACKING_CODE_LENGTH': 16, # اختیاری
   'SETTING_VALUE_READER_CLASS': 'azbankgateways.readers.DefaultReader', # اختیاری
   'BANK_PRIORITIES': [],

}

-----------------------------------------
urls:
from django.contrib import admin
from django.urls import path

from azbankgateways.urls import az_bank_gateways_urls
from payment.views import go_to_gateway_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bankgateways/', az_bank_gateways_urls()),
    path('gate-way/', go_to_gateway_view)
]



-------------------------------------------------
payment/views:
from django.urls import reverse
from azbankgateways import bankfactories, models as bank_models, default_settings as settings


def go_to_gateway_view(request):
    # خواندن مبلغ از هر جایی که مد نظر است
    amount = 1000
    # تنظیم شماره موبایل کاربر از هر جایی که مد نظر است
    user_mobile_number = '+989112221234'  # اختیاری

    factory = bankfactories.BankFactory()
    bank = factory.create()  # or factory.create(bank_models.BankType.BMI) or set identifier
    bank.set_request(request)
    bank.set_amount(amount)
    # یو آر ال بازگشت به نرم افزار برای ادامه فرآیند
    bank.set_client_callback_url('/callback')
    bank.set_mobile_number(user_mobile_number)  # اختیاری

    # در صورت تمایل اتصال این رکورد به رکورد فاکتور یا هر چیزی که بعدا بتوانید ارتباط بین محصول یا خدمات را با این
    # پرداخت برقرار کنید.
    bank_record = bank.ready()

    # هدایت کاربر به درگاه بانک
    return bank.redirect_gateway()


-------------------------------------------
bmi.py:
import logging
import base64
import datetime

import requests
from Crypto.Cipher import DES3

from azbankgateways.banks import BaseBank
from azbankgateways.exceptions import SettingDoesNotExist, BankGatewayConnectionError
from azbankgateways.exceptions.exceptions import BankGatewayRejectPayment, BankGatewayStateInvalid
from azbankgateways.models import CurrencyEnum, BankType, PaymentStatus
from azbankgateways.utils import get_json


class BMI(BaseBank):
    _merchant_code = None
    _terminal_code = None
    _secret_key = None

    def __init__(self, **kwargs):
        super(BMI, self).__init__(**kwargs)
        self.set_gateway_currency(CurrencyEnum.IRR)
        self._token_api_url = 'https://sadad.shaparak.ir/vpg/api/v0/Request/PaymentRequest'
        self._payment_url = "https://sadad.shaparak.ir/VPG/Purchase"
        self._verify_api_url = 'https://sadad.shaparak.ir/vpg/api/v0/Advice/Verify'

    def get_bank_type(self):
        return BankType.BMI

    def set_default_settings(self):
        for item in ['MERCHANT_CODE', 'TERMINAL_CODE', 'SECRET_KEY']:
            if item not in self.default_setting_kwargs:
                raise SettingDoesNotExist()
            setattr(self, f'_{item.lower()}', self.default_setting_kwargs[item])

    def get_pay_data(self):
        time_now = datetime.datetime.now().strftime('%m/%d/%Y %H:%M:%S %P')
        data = {
            'TerminalId': self._terminal_code,
            'MerchantId': self._merchant_code,
            'Amount': self.get_gateway_amount(),
            'SignData': self._encrypt_des3(
                '{};{};{}'.format(
                    self._terminal_code,
                    self.get_tracking_code(),
                    self.get_gateway_amount(),
                )
            ),
            'ReturnUrl': self._get_gateway_callback_url(),
           # 'LocalDateTime': time_now,
change to 'LocalDateTime': datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S"),
            'OrderId': self.get_tracking_code(),
            'AdditionalData': 'oi:%s-ou:%s' % (self.get_tracking_code(), self.get_mobile_number()),
        }
        return data

    def prepare_pay(self):
        super(BMI, self).prepare_pay()

    def pay(self):
        super(BMI, self).pay()
        data = self.get_pay_data()
        response_json = self._send_data(self._token_api_url, data)
        if response_json['ResCode'] == '0':
            token = response_json['Token']
            self._set_reference_number(token)
        else:
            logging.critical("BMI gateway reject payment")
            raise BankGatewayRejectPayment(self.get_transaction_status_text())

    """
    : gateway
    """
    def _get_gateway_payment_method_parameter(self):
        return "GET"

    def _get_gateway_payment_url_parameter(self):
        return self._payment_url

    def _get_gateway_payment_parameter(self):
        params = {
            'Token': self.get_reference_number()
        }
        return params

    def get_verify_data(self):
        super(BMI, self).get_verify_data()
        data = {
            'Token': self.get_reference_number(),
            'SignData': self._encrypt_des3(self.get_reference_number()),
        }
        return data

    def prepare_verify(self, tracking_code):
        super(BMI, self).prepare_verify(tracking_code)

    def verify(self, transaction_code):
        super(BMI, self).verify(transaction_code)
        data = self.get_verify_data()
        response_json = self._send_data(self._verify_api_url, data)
        if response_json['ResCode'] == '0':
            self._set_payment_status(PaymentStatus.COMPLETE)
            extra_information = f"RetrivalRefNo={response_json['RetrivalRefNo']},SystemTraceNo={response_json['SystemTraceNo']}"
            self._bank.extra_information = extra_information
            self._bank.save()
        else:
            self._set_payment_status(PaymentStatus.CANCEL_BY_USER)
            logging.debug("BMI gateway unapprove payment")

    def prepare_verify_from_gateway(self):
        super(BMI, self).prepare_verify_from_gateway()
        request = self.get_request()
        for method in ['POST', 'GET', 'data', 'PUT']:
            token = getattr(request, method, {}).get('token', None)
            if token:
                break
        if not token:
            raise BankGatewayStateInvalid
        self._set_reference_number(token)
        self._set_bank_record()

    def verify_from_gateway(self, request):
        super(BMI, self).verify_from_gateway(request)

    @classmethod
    def _pad(cls, text, pad_size=16):
        text_length = len(text)
        last_block_size = text_length % pad_size
        remaining_space = pad_size - last_block_size
        text = text + (remaining_space * chr(remaining_space))
        return text

    def _encrypt_des3(self, text):
        secret_key_bytes = base64.b64decode(self._secret_key)
        text = self._pad(text, 8)
        cipher = DES3.new(secret_key_bytes, DES3.MODE_ECB)
        cipher_text = cipher.encrypt(str.encode(text))
        return base64.b64encode(cipher_text).decode("utf-8")

    def _send_data(self, api, data):
        try:
            response = requests.post(api, json=data, timeout=5)
        except requests.Timeout:
            logging.exception("BMI time out gateway {}".format(data))
            raise BankGatewayConnectionError()
        except requests.ConnectionError:
            logging.exception("BMI time out gateway {}".format(data))
            raise BankGatewayConnectionError()

        response_json = get_json(response)
        self._set_transaction_status_text(response_json['Description'])
        return response_json

**Comment by ali-zahedi** [comment]
چیزی که بنظر میاد اینه که:

1. کلاس بانک ملی رو تغییر دادید. لطفا حتما پکیج رو به صورت مستقل نصب کنید و فعلا از تغییر دادن اون پرهیز کنید تا اگر موردی هست پیدا بشه. بعد اگر خواستید قابلیت یا فیچری رو اضافه کنید بتونید انجام بدید 
2.  `BANK_PRIORITIES`: بانک ملی رو در لیست قرار بدید و این تنظیم رو مقدار دهی کنید.
3. یو آر ال بازگشت هم وجود ندارد. ( الان خیلی اهمیتی نداره ولی به صورت کلی عرض کردم) 

درگاه بانک ملی تست شد و مشکلی نداشت

**Comment by masiha972** [comment]
من دوباره یک پروژه جدید درست کردم و این کارهایی که فرمودین انجام دادم ولی دوباره ارور داد
![Capture](https://user-images.githubusercontent.com/60233700/129441438-005d06c3-d378-448d-a5b8-10b2390bb50e.JPG)

**Comment by ali-zahedi** [comment]
این مورد روی ورژن `1.6.12` رفع شد. 
می تونید پکیج رو آپدیت کنید به ورژن ذکر شده و استفاده کنید. 

اگر مورد دیگه ای هم بود لطفا درنگ نکنید و ایشو جدیدی رو باز کنید.

**Comment by masiha972** [comment]
ببخشید دوباره مزاحم میشم

![Capture](https://user-images.githubusercontent.com/60233700/129442150-20ea7e06-90b9-460d-909b-37a803437503.JPG)



![Capture2](https://user-images.githubusercontent.com/60233700/129442158-339b3c00-d7bc-4e27-b27d-a2526a3c3ee2.JPG)
