### ISSUE TITLE
BankGatewayRejectPayment at /bank اطلاعات SignData ارسالی اشتباه است

### ISSUE THREAD

**Issue by masiha972** [ali-zahedi/az-iranian-bank-gateways#21]

**Comment by masiha972** [comment]
![Uploading Capture.JPG…]()

![Uploading Capture2.JPG…]()

**Comment by masiha972** [comment]
ببخشید دوباره مزاحم میشم
![Capture](https://user-images.githubusercontent.com/60233700/129442234-76857981-624c-4c49-b512-e14bb048080b.JPG)

![Capture2](https://user-images.githubusercontent.com/60233700/129442236-26758c2f-7b40-41fb-8390-cbe688be9e2e.JPG)

**Comment by ali-zahedi** [comment]
حتما مطمئن شوید که تغییری در کد نداشته باشید
ورژن پکیج رو میفرمایید؟

**Comment by masiha972** [comment]
1.6.12

**Comment by ali-zahedi** [comment]
خروجی pip freeze رو لطفا میشه قرار بدید اینجا؟

**Comment by masiha972** [comment]
چشم

**Comment by masiha972** [comment]
بفرمایید:

appdirs==1.4.4
asgiref==3.4.1
attrs==21.2.0
az-iranian-bank-gateways==1.6.12
cached-property==1.5.2
certifi==2021.5.30
charset-normalizer==2.0.4
defusedxml==0.7.1
Django==3.2.6
idna==3.2
isodate==0.6.0
lxml==4.6.3
pycryptodome==3.10.1
pytz==2021.1
requests==2.26.0
requests-file==1.5.1
requests-toolbelt==0.9.1
six==1.16.0
sqlparse==0.4.1
urllib3==1.26.6
zeep==4.0.0

**Comment by ali-zahedi** [comment]
@masiha972 لطفا به ایمیل من یه پیغام بدید من بتونم روی محیط شما تست بگیرم با هم بررسی کنیم مورد رو . 
alizahedigol روی جیمیل

**Comment by ali-zahedi** [comment]
لطفا از فایل `bmi.py`
خروجی های زیر رو به اشتراک بگذارید:

1. خروجی متد get_pay_data
2. همچنین خروجی متغیر ‍‍`response_json` در متد `pay`

**Comment by masiha972** [comment]
بفرمایید
---------------------------------------------
{'TerminalId': '*', 'MerchantId': '*', 'Amount': 1000, 'SignData': 'hbs3krTdqcmXJC5I5B/Z084OjuVfRqlhXqMrPOBR4yQ=', 'ReturnUrl': 'http://127.0.0.1:8000/bankgateways/callback/?bank_type=BMI&identifier=1', 'LocalDateTime': '08/14/2021 15:22:15 PM', 'OrderId': 7179343609162965, 'AdditionalData': 'oi:7179343609162965-ou:+989112221234'}
-------------------------------------------------
{'ResCode': '1025', 'Token': None, 'Description': 'اطلاعات SignData ارسالی اشتباه است'}

**Comment by ali-zahedi** [comment]
لطفا خروجی این مقدار این تابع رو هم در فایل `bmi.py` ‍‍قرار بدید

‍‍```
self._encrypt_des3('12077333;7179343609162965;1000')
```

**Comment by masiha972** [comment]
OcfAnfE3imOXJC5I5B/Z084OjuVfRqlhXqMrPOBR4yQ=

**Comment by masiha972** [comment]
بفرمایید

**Comment by ali-zahedi** [comment]
ببخشید یادم رفت متغیر سکرت کی رو تغییر بدیم.

1. `SECRET_KEY` = `F9MfmIouNsA+e+VsaNoV2nxpG8YxgG7b` در تنظیمات جایگزین شود
2. `secret_key_bytes` در متد `_encrypt_des3`
3. `text` در متد `_encrypt_des3`
4. `cipher` در متد `_encrypt_des3`
5. `cipher_text` در متد `_encrypt_des3`

این مقادیر رو هم خروجیش رو ارسال بفرمایید

**Comment by ali-zahedi** [comment]
چیزی که بنظر میاد این هست که مقدار `SECRET_KEY` رو اشتباه ست کردید برای همین خطای مطرح شده را دریافت می کنید.

**Comment by masiha972** [comment]
b'\x17\xd3\x1f\x98\x8a.6\xc0>{\xe5lh\xda\x15\xda|i\x1b\xc61\x80n\xdb' 

24000615;1959584536622141;1000 

<Crypto.Cipher._mode_ecb.EcbMode object at 0x0000017CC308C8E0> 

b'\xee\xe1\x95\x05f9\x17\xbe\x00\x98\xc7\xc59J\x95\t,\xc49\xef\xad/c\xf8\xd0\x1b\\zr/\xf5I'

بفرمایید

**Comment by ali-zahedi** [comment]
نتیجه نهایی رو هم ارسال می کنید با کلید جدید؟

**Comment by masiha972** [comment]
باز هم همون ارور قبلی رو میده

این بانک ملی merchant key تستی نداره؟

**Comment by ali-zahedi** [comment]
منظورم از خروجی 
لطفا خروجی این مقدار این تابع رو هم از فایل bmi.py ‍‍قرار بدید

self._encrypt_des3('12077333;7179343609162965;1000')

بود.

**Comment by masiha972** [comment]
9+KC8NitGFQo0ZgE++KraTBy078HUWeH9ozrti558Wc=

**Comment by ali-zahedi** [comment]
خروجی متد درست هست و موردی نداره. همونطور که عرض کردم: 
چیزی که بنظر میاد این هست که مقدار `SECRET_KEY` رو اشتباه ست کردید برای همین خطای مطرح شده را دریافت می کنید.
تا جایی که می دونم میتونید این کلید رو دوباره تولید کنید. شاید دوباره تولید شده و در اختیار شما نیست و یا اشتباهی با کلید درگاه دیگه ای جا به جا گذاشتید. 
مجدد تولیدش کنید از پنل بانک ملی و قرارش بدید. 

این طرف مشکلی بنظر نمیاد. 

چون خروجی ها بنظر درست هستند.

**Comment by masiha972** [comment]
بسیار ممنون از زمانی که گذاشتید

زحمت کشیدید واقعا
