### ISSUE TITLE
خطای آدرس هدایت شده برای پرداخت

### ISSUE THREAD

**Issue by reza78gh** [ali-zahedi/az-iranian-bank-gateways#22]
سلام، خسته نباشید.
من طبق آموزش برای بانک ملی تا مرحله ارسال به بانک پیش رفتم ولی وقتی ادرس پرداخت وارد میکنم به بانک منتقل میشم و خطای آدرس هدایت شده برای پرداخت ، در محدوده آدرس های اعلام شده از طرف پذیرنده نمی باشد . دریافت میکنم
ادرس آی پی و دامنه اعلام شده به بانک هم تغییر نکرده، به نظر شما مشکل از کجا میتونه باشه

**Comment by ali-zahedi** [comment]
سلام وقت بخیر. 
لطفا برای شروع:

1. ورژن پکیجی که در حال استفاده از اون هستید
2. خروجی رکورد دیتابیس مربوطه رو به صورت کامل. 

اینجا قرار بدید

با تشکر

**Comment by reza78gh** [comment]
1. az-iranian-bank-gateways==1.6.12
2. https://s19.picofile.com/file/8440210592/azbankgateways_bank.txt.html
بخشی از خروجی دیتابیس به صورت مرتب در فایل اکسل(https://s18.picofile.com/file/8440210542/azbankgateways_bank.xlsx.html)

**Comment by ali-zahedi** [comment]
درود مجدد. 
ببخشید در این چند مدت مقداری درگیر بودم. 
تنظیمی رو اضافه کردم با عنوان 
‍‍`'IS_SAMPLE_FORM_ENABLE': True, `
که در راهنما هم قرار دادم. 
بعد از فعال کردن این قسمت میتونید از طریق آدرس زیر پرداختی رو به عنوان نمونه امتحان کنید. 

http://127.0.0.1:8000/bankgateways/sample-payment/

ممنون میشم نتیجه رو اینجا هم قرار بدید.

**Comment by reza78gh** [comment]
سلام،وقتتون بخیر
متاسفانه بازم با درگاه سداد به خطای آدرس هدایت شده مواجه شد
با درگاه زرین پال مشکلی نداره و انجام میشه

**Comment by ali-zahedi** [comment]
ممکن هست روی ایمیل alizahedigol روی جیمیل به من پیام بدید تا با هم بتونیم بررسی کنیم؟

**Comment by ali-zahedi** [comment]
مجموع بررسی بر این بود که مشکل از سمت بانک ملی است و نیازمند تقاضای شما برای پشتیبانی از بانک ملی است برای ثبت دامنه. 

لطفا اگر مشکل حل نشد حتما این ایشو رو مجدد باز کنید تا بررسی کنیم.
