### ISSUE TITLE
اتصال یوزر به درگاه

### ISSUE THREAD

**Issue by feredy** [ali-zahedi/az-iranian-bank-gateways#24]
سلام جناب زاهدی ، بنده میخواستم بدونم که چطور باید یوزری که پرداخت رو انجام داده در رکورد نمایش داد و همیچنین چطور میتونم از دستورات شرطی استفاده کنم ؟ برای مثال 
if status == complete:
< button > form < button >
که اگر کاربر پرداخت کرده مبلغ رو یک دکمه در پروفایلش مشخص بشه ، ممنون میشم کمکم کنید با تشکر
وهمچنین چطور میتونم کوئری ست ایجاد کنم ازش ؟

**Comment by ali-zahedi** [comment]
سلام وقت بخیر. 
در ساده ترین حالت برای این کار باید یک جدول تعریف کنید که آی دی رکورد درگاه بانک بهمراه اطلاعات یوزر رو در اون ذخیره کنید. 

میتونید از منابع آنلاین و آموزشی برای یادگیری جنگو و پایتون استفاده کنید.

**Comment by feredy** [comment]
درسته خیلی ممنون

**Comment by nimaes80** [comment]
user = 

> سلام وقت بخیر. در ساده ترین حالت برای این کار باید یک جدول تعریف کنید که آی دی رکورد درگاه بانک بهمراه اطلاعات یوزر رو در اون ذخیره کنید.
> 
> میتونید از منابع آنلاین و آموزشی برای یادگیری جنگو و پایتون استفاده کنید.

نمیشه این یه خط کد رو به مد اضافه کنی؟


‍
```

from django.contrib.auth import get_user_model

User = get_user_model()

user = models.ForeignKey(User, on_delete=models.RESTRICT)
```
