### ISSUE TITLE
تابع bpSettleRequest   در درگاه ملت 

### ISSUE THREAD

**Issue by alip990** [ali-zahedi/az-iranian-bank-gateways#27]
سلام ، داکیومنت های درگاه پرداخت ملت و کدتون رو بررسی میکردم یه تابع به اسم bpSettleRequest بعد از تایید شدن تراکنش باید فراخوانی شود . چنین تابعی توی کد وجود نداشت 
چنین توضیحی در داکیومنت هست 
![image](https://user-images.githubusercontent.com/46352990/145777582-ac6f443c-a943-4cbe-9b99-b135bdaadd62.png)

![image](https://user-images.githubusercontent.com/46352990/145777467-8f1dfb1a-2dfc-4139-8304-c768c112efc7.png)
البته هنوز کارکرد کد رو تست نکردم ، صرفا بررسی کردم .

**Comment by ali-zahedi** [comment]
@alip990 سلام و روز بخیر خدمت شمال علی عزيز. 
من متاسفانه دسترسی به درگاه بانک ملت ندارم و درگاه بانک ملت توسط بقیه دوستان توسعه داده شده. اگر بتونید پی آر متناسب با اون رو آماده کنید یا شرایطی رو فراهم کنید که کمک کنید بتونید تکمیل/اصلاح کنیم عالی میشه. 
همچنین از شما درخواست دارم که اگر میتونید تست رو انجام بدید که فانکشنالیتی برای درگاه بانک ملت به درستی کار می کند یا نه. 

از اشتراك و صرف زمان شما ممنون هستم. قطعا در زمان بقیه دوستان صرفه جویی می کنید.
