### ISSUE TITLE
customizing redirect_gateway to integrate with rest framework

### ISSUE THREAD

**Issue by sina-am** [ali-zahedi/az-iranian-bank-gateways#28]
سلام. من توی استفاده از این کتابخونه در یک پروژه با rest framework  به مشکل خودم.
مشکل اینه که قراره قسمت ریدایرکت شدن کاربر به درگاه بانک در فرانت انجام بشه و در بک‌اند یک api برای اماده کردن درگاه بانکی و فرستادن اطلاعات لازم برای وصل شدن به درگاه بانکی به فرانت ارسال بشه. اما تابعی که برای اینکار وجود داره (redirect_gateway)  هم کار ست کردن PaymentStatus رو انجام می‌ده و هم اینکه برنامه رو به یک تابع دیگه برای گرفتن اطلاعات درگاه بانکی ریدایرکت میکنه.
که این ریدایرکت کردن باعث میشه نشه توی یک ای‌پی‌ای responseای رو به کاربر برگردوند.
گفتم بپرسم آیا راهی برای انجام اینکار بدون تغییر کدها وجود داره؟

روشی که به ذهنم رسید برای حلش این بود که توی تابع redirect _gateway قسمت چک کردن و ست کردن PaymentStatus رو از قسمت ریدایرکت جدا کنم
و یک تابع فقط برای نشون دادن اطلاعات درگاه(به جای ریدایرکت کردن) به وجود بیارم
کدی شبیه به این:

`    
    def _prepare_redirect(self):
        if (timezone.now() - self._bank.created_at).seconds > 120:
            self._set_payment_status(PaymentStatus.EXPIRE_GATEWAY_TOKEN)
            logging.debug("Redirect to bank expire!")
            raise BankGatewayTokenExpired()
        logging.debug("Redirect to bank")
        self._set_payment_status(PaymentStatus.REDIRECT_TO_BANK)

    def redirect_gateway(self):
        """کاربر را به درگاه بانک هدایت می کند"""
        self._prepare_redirect()
        return redirect(self.get_gateway_payment_url())

    def create_gateway_payment(self):
        self._prepare_redirect()
        params = self._get_gateway_payment_parameter()
        params.update({
            'url': self._get_gateway_payment_url_parameter(),
            'method': self._get_gateway_payment_method_parameter(),
        })
        return params

**Comment by ali-zahedi** [comment]
بنظرم میاد که ریدایرکت خارج از فریم ورک کار درستی نیست. چون هم ست کردن پارامتر ها و هم ست کردن متد ها (گت یا پست بودنشون) میتونه ایجاد دردسر کنه.  (بعضی از بانک ها با پست کار میکنند و بعضی با گت)
بهترین کار این هست که شما یک مسیری رو در سمت خود اپ طراحی کنید و بعد در قدم نهایی از این قسمت کاربر رو به سمت بانک هدایت کنید. 

یا اینکه اگر مایل هستید صفحه ای که از داخل فریم ورک هست رو شخصی سازی کنید میشه این صفحه رو به عنوان پارامتر از داخل اپ دریافت کرد یا اینکه بلاکی رو براش نوشت که این فرم داخل اون اجرا بشه. 

اگر نظر دیگه ای داری یا چیز دیگه ای به ذهنت میرسه لطفا ارسال کن با هم بررسی کنیم

**Comment by sina-am** [comment]
متوجه شدم. من اول ذهنیتم این بود که چون اپ قراره فقط اطلاعت مورد نیاز فرانت رو براش بفرسته بهتره که بحث ریدایرکت هم با خود فراند انجام بشه.
اره اگه بشه صفحه خود فریم ورک رو هم شخصی سازی کرد خوب می‌شه هرچند که فکر کنم اگه قرار باشه کار ریدایرکت با خود اپ انجام بشه حداقل برای این پروژه ‌ای که دارم چندان نیازی نباشه.

ممنون بابت راهنمایی.
