### ISSUE TITLE
اضافه کردن درگاه نکست پی

### ISSUE THREAD

**Issue by takweb12** [ali-zahedi/az-iranian-bank-gateways#29]
سلام
دمتون گرم
اگه امکانش هست درگاه نکست پی رو هم بهش اضافه کنید
nextpay-ir
باتشکر

**Comment by ali-zahedi** [comment]
بر اساس این کامنت https://github.com/ali-zahedi/az-iranian-bank-gateways/pull/76#issuecomment-2067620877 
بنظر فعلا متوقف شده نکست پی.
