### ISSUE TITLE
#Error Unknown field(s) (pk) specified for Bank. Check fields/fieldsets/exclude attributes of class BankAdmin.

### ISSUE THREAD

**Issue by erfanmosaddeghi** [ali-zahedi/az-iranian-bank-gateways#3]
در قسمت ادد کردن بانک ارور داره. مشکل داره یا کار دیگه ای باید انجام بشه ممنون میشم راهنمایی کنید

**Comment by ali-zahedi** [comment]
ممنونم از گزارش موضوع. 
بله بخاطر این هست که فیلد `pk` در read_only پنل مدیریت ادد نشده. 

اضافه می کنم و مرج می کنم.
