### ISSUE TITLE
ارسال اطلاعات اضافه هنگام ریدایرکت

### ISSUE THREAD

**Issue by mojtabaakbari221b** [ali-zahedi/az-iranian-bank-gateways#32]
اگر امکانی فراهم میشد که یکسری اطلاعات اضافه به اون ویو که به یوآرال که از سمت بانک برمیگردد ارسال کرد خیلی خوب میشد .
منظورم اینه مثلا وقتی ما داریم یه سبد خریدو پرداخت میکنیم، اون کاربر رو بعد بازگشت از پرداخت به یه صفحه دیگه میخوایم هدایت کنیم که بعد کلیک یه گزینه ای دوباره بتونه برگرده به همون سبد خرید
اگه بشه این امکان خیلی خوب میشه

**Comment by ali-zahedi** [comment]
@mojtabaakbari221b این امکان در حال حاضر وجود دارد. 
شما میتونید با استفاده از 
```python
bank.set_client_callback_url(reverse('callback-gateway'))
```
هر پارامتری اضافه کنید و درهنگام بازگردانی آن را دریافت کنید. 
برای اطلاعات بیشتر میتونید به [اینجا](https://docs.djangoproject.com/en/4.0/ref/urlresolvers/#reverse) مراجعه کنید. 

اگر مشکلتون حل نشد حتما در ادامه مطرح کنید

**Comment by mojtabaakbari221b** [comment]
خیلی متشکرم
