### ISSUE TITLE
BankGatewayAutoConnectionFailed at

### ISSUE THREAD

**Issue by janinejad** [ali-zahedi/az-iranian-bank-gateways#34]

**Comment by ali-zahedi** [comment]
@janinejad سلام و وقت بخیر. 
ممنون میشم اگر توضیحی برای این مورد دارید ارسال کنید. 
من این ایشو رو میبندم اگر توضیحات و استک و پارامتر ها رو اضافه کنید راحت تر میشه بررسی اش کرد. همچنین برای دوباره باز کردنش راحت باشید .
