### ISSUE TITLE
zarinpal sandbox gateway

### ISSUE THREAD

**Issue by hamidrasti** [ali-zahedi/az-iranian-bank-gateways#35]
باسلام. تشکر بابت پکیج بسیار خوبتون. چگونه باید کاربر رو به درگاه پرداخت sandbox زرین پال هدایت کنیم؟ (برای تست درگاه پرداخت)

برای IDPAY کانفیگ X_SANDBOX در تنظیمات وجود داره ولی برای زرین پال چیزی ندیدم. ممنون میشم راهنمایی کنید.

**Comment by ali-zahedi** [comment]
@hamidrasti سلام و عرض ادب. 
فکر می کنم این امکان در ورژن جدید زرین پال هست که باید بروزرسانی بشه. 
اگه وقت داشته باشی خوشحال میشم مرج ریکوئست این رو آماده کنی و بفرستی در غیر این صورت باید کمی منتظر بود که تایم خالی ایجاد بشه تا این تغییرات رو اضافه کنم.

**Comment by hamidrasti** [comment]
سلام علی جان. ببخشید بابت تاخیر در جواب دادن. من پنل زرین پال و کانفیگ هاشو دارم و روی این مورد کار میکنم و مرج ریکوئست رو میفرستم خدمتت.
احتمالا تا هفته سوم تیرماه تکمیل میشه این قضیه
