### ISSUE TITLE
تراکنش کی تکمیل(کامل) میشه؟؟؟

### ISSUE THREAD

**Issue by usefss** [ali-zahedi/az-iranian-bank-gateways#36]
سلام، 
با خوندن کد برام یکم ابهام پیش اومده...
توی مرحله اولیه وقتی که کاربر رو به درگاه بانک هدایت میکنیم وضعیت تراکنش در حالت `"Redirect to bank"` قرار میگیره...
توی مرحله بعد کاربر از درگاه بانک برمیگرده و ریدایرکت میشه به بکند و طبق کدی که خودتون قرار دادید 
```
def callback_gateway_view(request):
    tracking_code = request.GET.get(settings.TRACKING_CODE_QUERY_PARAM, None)
    if not tracking_code:
        logging.debug("این لینک معتبر نیست.")
        raise Http404

    try:
        bank_record = bank_models.Bank.objects.get(tracking_code=tracking_code)
    except bank_models.Bank.DoesNotExist:
        logging.debug("این لینک معتبر نیست.")
        raise Http404

    # در این قسمت باید از طریق داده هایی که در بانک رکورد وجود دارد، رکورد متناظر یا هر اقدام مقتضی دیگر را انجام دهیم
    if bank_record.is_success:
        # پرداخت با موفقیت انجام پذیرفته است و بانک تایید کرده است.
        # می توانید کاربر را به صفحه نتیجه هدایت کنید یا نتیجه را نمایش دهید.
        return HttpResponse("پرداخت با موفقیت انجام شد.")
```
بررسی میکنیم که آیا وضعیت این تراکنش در دیتابیس `is_success` یا همون `Completed` هست یا نه...
حالا سوال من اینه که دقیقا کی وضعیت تراکنش رو  `Completed` قرار میدیم و روی دیتابیس کوعری میزنیم و آپدیت میکنیم؟؟؟؟

**Comment by ali-zahedi** [comment]
@usefss سلام و عرض ادب. 
وضعیت تکمیل شده یا همون `completed` بسته به هر بانک پروسه متفاوتی رو ممکنه داشته باشه. ولی در حالت کلی به این صورت هست که زمانی که کاربر به بانک هدایت میشه وضعیت ریدایرکت رو میگیره. زمانی که کاربر بر میگرده مستقل از وضعیتش وضعیت ریترن رو میگیره بعد از این بلافاصله با توجه به پارامترهای برگشت داده شده، اگر کنسل شده باشند که وضعیت به کنسل تغییر پیدا میکنه ولی اگر موفقیت آمیز باشه پروسه وریفای شدن  پیمنت ( که معمولا درگاه ها اجازه میدن تا پانزده دقیقه بعد از پرداخت این پروسه رو انجام بدید و در صورت عدم انجامش پول رو بازگشت میزنند) انجام میشه که اونجا در صورتی که موفقیت آمیز باشه وضعیت تکمیل شده رو در نظر میگیره. روالی رو که توضیح دادم به صورت کلی هست که میتونه بسته به درگاه متفاوت باشه.

**Comment by usefss** [comment]
پروسه وریفای شدن پیمنت رو چطوری باید با این پکیج انجام بدیم؟؟؟

**Comment by ali-zahedi** [comment]
@ali-zahedi خودش بعد از اینکه از درگاه برمیگرده انجام میده و تکمیل میشه در صورتی که پرداخت موفق باشه.

**Comment by ali-zahedi** [comment]
> پروسه وریفای شدن پیمنت رو چطوری باید با این پکیج انجام بدیم؟؟؟

@usefss  خودش بعد از اینکه از درگاه برمیگرده انجام میده و تکمیل میشه در صورتی که پرداخت موفق باشه.

من پیشنهادم اینه که برای نمونه داشته باشید به هر درگاهی که دارید متصل کنید و حالت تست رو که در تنظیمات هست (در توضیحات پکیج میتونید پیداش کنید) رو فعال کنید و از اونجا پرداختی رو انجام بدید. همه چی به درستی باید کار کنه.
