### ISSUE TITLE
افزودن درگاه nextpay

### ISSUE THREAD

**Issue by hsdarestani** [ali-zahedi/az-iranian-bank-gateways#40]
@ali-zahedi 
با سلام
آیا امکان استفاده از درگاه و مستندات nextpay.org هم موجود هست؟ اگر خیر، امکان افزوده شدنش هست؟ :(

**Comment by ali-zahedi** [comment]
duplicate: #29 
این درخواست قبلا ثبت شده. میتونید اون ایشو رو آپ وت کنید. 

#29 

من این ایشو رو میبندم.

و اینکه بله امکانش هست. هم خودتون میتونید اضافه کنید و مرج ریکوئستش رو بفرستید که خیلی خوشحال خواهیم شد. هم اینکه اگر زمان خالی پیدا بشه من خودم این کار رو انجام میدم. (ولی در حال حاضر برنامه ای براش ندارم)
