### ISSUE TITLE
ست کردن درگاه پرداخت با ری‌اکت و جنگو

### ISSUE THREAD

**Issue by ar00783** [ali-zahedi/az-iranian-bank-gateways#41]
سلام. من میخام یه درگاه پرداخت IDPay ایجاد کنم. قسمت فرانت با ری‌اکت نوشته شده و قسمت بک‌اند با جنگو رست. لینک نسخه کوچیک شده رو برای حالت تست پایین گذاشتم.
ابتدا url های جنگو رو به اینصورت نوشتم(دقیقا همونایی که توی داکیومنتیشن هست):
...
path('go-to-gateway/', views.go_to_gateway_view),
...
و به view ها دست نزدم(فقط مبلغ رو از سمت فرانت میخونه)
توی قسمت فرانت، در خواست رو به صورت زیر به url بالا میفرستم(یه button گذاشتم، که submit میشه):

const data = {
    order_id: 1010,
    amount: 321000,
    callback: "https://google.com",
};
const response = await axios.post("go-to-gateway/", data)

بعد url نهایی پرداخت رو از خروجی response میگیرم:

url = response.request.responseURL

که مثلا همچین چیزی هست:

https://idpay.ir/p/ws-sandbox/7c6a31ca872446e24a55506dab57a134

و بعد میفرستمش به درگاه پرداخت نهایی:

window.location.replace(url)

ظاهرا که درست کار میکنه لااقل در حالت آزمایشی(sandbox=1).  هنوز با حالت واقعی امتحان نکردم. لینک گیتلب پروژه هم اینجا گذاشتم(اخیرا دیگه فیلتر نیست!):

https://gitlab.com/dotdjango/payment.git

خواستم بدون که این روش درسته؟ لطفا کدها رو چک کنین چون ممکنه خیلیا بخوان اینجوری استفاده کنن.
سپاس

**Comment by ali-zahedi** [comment]
@ar00783

  سلام در مورد این کار ایده ای ندارم ولی من باشم این کار رو انجام نمیدم. چون هیچ ضمانتی وجود نداره کاری که میخواید اتفاق بیفته. :) و این رو از طریق اکسپشن ها یا چیز های دیگه باید داخل برنامتون مدیریت کنید.

شما هر پروسه ای که لازم دارید رو قبلش باید برید. و بعدش یک ویو بنویسید که در واقع قدم آخر باشه. و کاربر رو هدایت کنید به اون ویو و بعد اون کاربر رو میفرسته به درگاه. حالا اونجا میتونید تعریف کنید که بعد از اینکه کارش تموم شد برگرده به سمت کلاینت شما. که حالا میخواد ری اکت باشه یا میخواد اپ نسخه موبایلتون باشه. 

 ---- 
در واقع شما فاکتور یا هر چیزی که دارید رو قبل از این چیزی که نوشتید انجام میدید و کارهاش رو انجام میدید و در نهایت در اون ویو با استفاده از فاکتور یا جالا هر چیزی که داده های کاربر رو دارید داخل نگهداری می کنید پروسه ارسال به درگاه بانک رو استارت میزنید.

امیدوارم که مفید بوده باشه.
