### ISSUE TITLE
درخواست از فرانت و نرفتن به سمت درگاه

### ISSUE THREAD

**Issue by dv1167** [ali-zahedi/az-iranian-bank-gateways#46]
سلام
من وقتی از درخواست پست "از سمت فرانت" میفرستم، این خروجی رو میگیرم توی بک‌اند(به سمت درگاه نمیره توی مرورگر، اما ارور هم نمیده):

"POST /idpay/ HTTP/1.1" 302 0
"OPTIONS /bankgateways/go-to-bank-gateway/?url=https .........  &method=GET HTTP/1.1" 200 0
"GET /bankgateways/go-to-bank-gateway/?url=https ......... &method=GET HTTP/1.1" 200 561

اما اگر همین درخواست رو با "پستمن" بفرستم این خروجی میاد و درگاه رو هم باز میکنه :

"POST /idpay/ HTTP/1.1" 302 0
"GET /bankgateways/go-to-bank-gateway/?url=https .......... &method=GET HTTP/1.1" 200 561

به نظرتون کجای کار ایراد داره که درگاه رو باز نمیکنه؟

**Comment by ali-zahedi** [comment]
@dv1167 نحوه استفاده شما اشتباه 

پروسه ارسال به بانک فقط و فقط باید از طریق ریدایرکت باشه. نه از طریق ای پی ای. 
اگر شما به ای پی ای نیاز دارید باید و باید به صورت جداگانه مراجل رو طی کنید و در آخر کاربر رو به این ویو هدایت کنید و بقیه مسیر طی بشه. 

-------
فرض کنید من میخواهم از طریق موبایل این کار رو انجام بدم. 
ای پی آی های مد نظر خودم را دارم. فاکتور رو و عملیاتم را از طریق آن ای پی ای ها انجام میدهم. در نهایت کاربر رو بهمراه شماره فاکتور به یک ویو هدایت میکنم از طریق مرورگر. در آن ویو فاکتور رو لود می کنم، شماره کاربر، مبلغ و ما بقی پارامتر ها رو ست می کنم و بقیه ماجرا که مثل اینکه پیاده کردید و کاربر رو هدایت می کنید به بانک.


-------
کاربر بر روی دکمه خرید کلیک می کند. 
۱- درخواست خرید از طریق ای پی آی ارسال می شود. پردازش صورت می گیرد. شماره فاکتور از طریق ای پی آي بازگردانده میشود. 
 ۲- پس از دریافت شماره فاکتور کاربر بهمراه شماره فاکتور به یک ویو ارسال میشود و بقیه ماجرا.

**Comment by ali-zahedi** [comment]
Duplicate: #41 
من ایشو رو بستم چون این یک باگ نیست. در صورتی که موردی دارید میتونید همینجا ادامه اش رو مطرح کنید. و در صورتی که باگی رو مشاهده کردید میتونید این ایشو رو با فشردن دکمه 
Reopen 
مجدد باز کنید. 

از ایجاد ایشو های جدید خودداری کنید.

**Comment by ali-zahedi** [comment]
نکته ای که فراموش کردم اضافه کنم در مورد پست من این هست که پست من یک مرورگر داره که صفحات اچ تی ام ال و جاوااسکریپت و  فرم ها رندر می کنه و در نتیجه اگر با جاواسکریپت کدی زده شده باشه رو سابمیت میکنه. 

در صورتی که وقتی شما فراخوانی رو به صورت یک درخواست انجام میدهید و پاسخ رو رندر نمی کنید بقیه فرم ها و ریدایرکت ها رو از دست خواهید داد.

**Comment by dv1167** [comment]
ممنون از شما 
همونجور که شما فرمودین من در ویو نهایی یه return redirect(url) دارم که کاربر رو هدایت میکنه به سمت درگاه. اما فراموشم شد که بگم توی لاگ مرورگر ارور cors origin میگیرم:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://idpay.ir/p/ws-sandbox/2d1e2b64f81e37a5321f4cb1b960f653. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 302

البته توی جنگو این تنظیمات انجام شده:

ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    ...
    'corsheaders',
]

CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
...
]

البته با پستمن همچین ایرادی رو ندارم.

**Comment by ali-zahedi** [comment]
همونطور که قبلا گفتم. پروسه اتون رو باید با ای پی برید. 
قسمت درگاه رو حتما باید با مرورگر برید. 

متنی که بالاتر نوشتم جواب شماست.
