### ISSUE TITLE
خطای بازگشت از درگاه

### ISSUE THREAD

**Issue by joejoe-am** [ali-zahedi/az-iranian-bank-gateways#48]
BankGatewayStateInvalid
You change the status bank record before/after this record change status from redirect to bank. current status is تکمیل شده
هنگام خرید موفق این برخی مواقع خطای 400 برمیگردونه و این اروری هست که برمیگردونه.

**Comment by ali-zahedi** [comment]
سلام و عرض ادب. 

اگر بتونین اطلاعات بیشتری در اختیار قرار بدین مثل استک و وضعیت رو تشریح کنید که چه اتفاقی میفته و چه اختلالی رو ایجاد میکنه بهتر میشه موضوع رو پیگیری کرد.

**Comment by joejoe-am** [comment]
سلام و وقت بخیر.
![Screenshot from 2022-08-15 11-49-53](https://user-images.githubusercontent.com/85931983/184592952-3ec0d7d6-8182-4670-bc65-2e45fc3f6235.png)

این همه اطلاعاتی هست که داریم و این وضعیت وقتی پیش میاد که پرداخت موفقیت آمیزه و کاربر روی دکمه بازگشت به سایت پذیرنده کلیک میکنه ارور 400 برمیگردونه ولی پرداخت انجام میشه.

**Comment by joejoe-am** [comment]
مشکل از سمت ما بود که کاربر رو به جای اشتباهی ریدایرکت میکردیم. خیلی ممنون بابت پیگیری سریعتون.
