### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by salehi1234** [ali-zahedi/az-iranian-bank-gateways#5]
با سلام
چرا پس از زدن دگمه ؛برگشت به سایت  پذیرنده ؛این ارور را میده
AttributeError at /bankgateways/callback/

'NoneType' object has no attribute 'callback_url'

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/bankgateways/callback/?bank_type=IDPAY&identifier=1&status=1&track_id=392426&id=545c7e3792bbdb1242a18798a2bb0b37&order_id=2899648918853678
Django Version: 	3.1.7
Exception Type: 	AttributeError
Exception Value: 	

'NoneType' object has no attribute 'callback_url'

ممنون میشوم کمکم کنید

**Comment by salehi1234** [comment]
منظور ما از ارور 


Request Method: | GET
-- | --
http://127.0.0.1:8000/bankgateways/callback/?bank_type=IDPAY&identifier=1&status=1&track_id=392426&id=545c7e3792bbdb1242a18798a2bb0b37&order_id=2899648918853678
3.1.7
AttributeError
'NoneType' object has no attribute 'callback_url'

**Comment by ali-zahedi** [comment]
سلام و وقت بخیر. 

در هنگام ارسال به درگاه 
‍`set_client_callback_url('آدرسی که قصد برگشت به آن را دارید')` 
را ست نکردید. برای همین موقع برگشت از درگاه با خطا مواجه می شوید. 

@salehi1234
