### ISSUE TITLE
BankGatewayAutoConnectionFailed at /go-to-getway

### ISSUE THREAD

**Issue by TahaAhvazi** [ali-zahedi/az-iranian-bank-gateways#50]
![Screenshot 2022-09-19 002421](https://user-images.githubusercontent.com/86960501/190925874-93e928e0-dc14-4c85-99f6-c8329d30838d.png)
با عرض سلام!
این ارور موقع رفتن به به اندپوینت go-to-getways نشون داده میشه !
No exception message supplied
Request Method: GET
Request URL http://127.0.0.1:8000/go-to-getway
Django Version:4.1.1
Exception Type:BankGatewayAutoConnectionFailed
Exception Location:Desktop\paydjango\env\lib\site-packages\azbankgateways\bankfactories.py, line 60, in auto_create
Python Version:3.10.6

**Comment by ali-zahedi** [comment]
سلام وقت بخیر. 
اکسپشن از نوع 

AutoConnectionFailed 

زمانی ایجاد میشه که به صورت کلی هیچ درگاهی تعریف نشده باشه یا هیچ درگاهی برای اتصال در دسترس نباشه یا همه درگاه ها با خطا مواجه باشند. 

به عنوان مثال شما درگاهی رو از پروایدر ایکس دریافت کردید، اطلاعات مد نظر رو در پروژه جنگو هم تعریف کردید. ولی برای پروایدر ایکس حتما باید آی پی رو هم اعلام کنید که شما اینکار رو انجام ندادید یا اگر انجام دادید برای سرورتون انجام دادید و الان دارید از روی ماشین خودتون امتحان می کنید( که آی پی متفاوتی داره) در نتیجه درخواست شما برای اتصال به درگاه از طرف پروایدر رد میشه. طبیعتا سیستم میره سراغ پروایدر بعدی و بعدی اینقدر این کار رو انجام میده تا همه ی پروایدر هایی که شما دارید رو رفته باشه. اگر هیچ پروایدری باقی نموند با این خطا روبرو میشید. 

* منظور از پروایدر درگاه بانک هست. 


حالا یا شما :

۱- هیچ پروایدری رو به سیستم معرفی نکردید
۲- یا پروایدر ها هیچ کدوم در دسترس نیستند
۳- یا شرط لازم مثل تعریف آی پی رو برای اون پروایدر انجام ندادید. دقت کنید آی پی یک مثال هست. 

پیشنهادم اینه که برای راه اندازی اولیه از سندباکس (حالت دیباگ پروایدر ها) آی دی پی یا زرین پال استفاده کنید. این حالت رو فعال کنید و کدتون رو تست بگیرید.

**Comment by ali-zahedi** [comment]
@TahaAhvazi من این ایشو رو میبندم چون فکر نمی کنم مورد مربوط به این پکیج باشه. 

در صورتی که متصور هستید این مورد مرتبط با پکیج هست، حتما این ایشو رو دوباره باز کنید و اطلاعات بیشتری رو ایجا به اشتراک بگذارید. 

مثل اینکه از چه درگاهی استفاده می کنید، (یا چه درگاه هایی) ترتیبشون چی هست، آیا موارد بالا رو انجام دادید یا نه و ...
