### ISSUE TITLE
BankGatewayAutoConnectionFailed

### ISSUE THREAD

**Issue by OmarFatahiDev** [ali-zahedi/az-iranian-bank-gateways#53]
سلام قربان خسته نباشید.
بعد از یکی دو بار استفاده در حالت سندباکس به این ارور برخوردم:
![image](https://user-images.githubusercontent.com/102545763/204015067-7a9553a7-78f7-40c4-9e95-11f68fda3dab.png)
![image](https://user-images.githubusercontent.com/102545763/204015108-0f408654-a8d5-4f47-884c-d4553726038b.png)

**Comment by ali-zahedi** [comment]
@OmarFatahiDev سلام این ارور زمانی هست که هیچ درگاهی برای اتصال موجود نباشه و یا همه ی درگاه هایی که شما معین کردید درخواست اتصال شما رو رد کنند. 

برای دیباگ بهتر بنظرم از حالت اتو کانکت بردارید و با حالت اتصال مستقیم وصل بشید که بتونید خطا رو ببینید.
