### ISSUE TITLE
 ModuleNotFoundError: No module named 'azbankgateways'

### ISSUE THREAD

**Issue by OmarFatahiDev** [ali-zahedi/az-iranian-bank-gateways#54]
به این ارور هم وقتی می خواستم که دیپلویش کنم بر خوردم.
![image](https://user-images.githubusercontent.com/102545763/205308834-d98f9082-5a50-4cfa-963d-7ffc2526759f.png)

**Comment by ali-zahedi** [comment]
@OmarFatahiDev 
لطفا این اطلاعات رو در اختیار قرار بدید.

```pip freeze ```

**Comment by OmarFatahiDev** [comment]
قربان خیلی خیلی زیاده اصلا نمیشه کپی یا ازش عکس گرفت

**Comment by ali-zahedi** [comment]
```pip freeze |grep -i az ```

این رو اجرا بفرمایید.

**Comment by OmarFatahiDev** [comment]
az-iranian-bank-gateways==1.8.2                                                                                                                     
python-amazon-simple-product-api==2.2.11

**Comment by ali-zahedi** [comment]
بنظر میاد که پکیج نصب هست. 
احتمال داره که از ویرچوآل اینوایرونمنت ها استفاده کرده باشید و ویرچوآل اینوایرونمنتتون رو فعال نکرده باشید.
