### ISSUE TITLE
	 'azbankgateways' is not a registered namespace

### ISSUE THREAD

**Issue by elm2013** [ali-zahedi/az-iranian-bank-gateways#55]
![Screenshot 2022-12-11 093657](https://user-images.githubusercontent.com/17771584/206889078-4b89490c-17fa-42dc-9ae5-bc36271d890c.png)
### این خطا بابت چیه و برای رفعش چیکار میتونم انجام بدم؟

**Comment by ali-zahedi** [comment]
@elm2013 مطابق با راهنما نصب بفرمایید. 

 بنظر میاد نیم اسپیس یو آر ال یا نصب نکردید یا تغییر نام دادید. 
برای نصب دقیق لطفا از راهنمایی که موجود هست استفاده کنید.
