### ISSUE TITLE
NoReverseMatch Reverse for '?tc=5075716874649973' not found. 

### ISSUE THREAD

**Issue by hypy13** [ali-zahedi/az-iranian-bank-gateways#58]
سلام

این خطا رو وقتی از درگاه پرداخت بر میگردم میخورم
مشکل از اینجاست که callback_url توی دیتابیس ذخیره نمیشه

کد درگاه پرداخت هم این هست
```

    def create_factor(self, subscription):
        factory = bankfactories.BankFactory()
        bank = factory.create()
        bank.set_request(self.request)
        bank.set_amount(subscription.price)
        bank.set_client_callback_url(reverse('subscription-gateway'))
        bank.set_mobile_number(self.request.user.phone_number)
        bank_obj = bank.ready()
```

```
return Response({
            "payment_url": bank.get_gateway_payment_url(),
        })
```

تا اینجا همه چی درسته
حتی bank.get_client_callback_url()
این رو هم پرینت میگیرم مقدار درستی رو نمایش میده

ولی بعد پرداخت url درست نیست و فقط همین رو برمیگردونه '?tc=5075716874649973' 

مشکل از کجاست؟

**Comment by hypy13** [comment]
یه نکته فقط

```
 def create_factor(self, subscription):
        factory = bankfactories.BankFactory()
        bank = factory.create()
        bank.set_request(self.request)
        bank.set_amount(subscription.price)
        bank.set_client_callback_url(reverse('subscription-gateway'))
        bank.set_mobile_number(self.request.user.phone_number)
        bank_obj = bank.ready()
        
        **bank._bank.save()**
```
این خط کد bank._bank.save() رو میزارم مشکل حل میشه

**Comment by ali-zahedi** [comment]
@hypy13 سلام حسین جان وقت بخیر. 

امیدوارم خوب بوده باشی. 

میشه `IS_SAMPLE_FORM_ENABLE` رو فعال کنی و با اون چک کنی؟

اگه خطا همچنان پا برجا بود لطفا حتما ورژنی که استفاده می کنی + از چه درگاهی داری استفاده می کنی + خطایی که میخوری رو به اشتراک بزار لطفا.

**Comment by hypy13** [comment]
خیلی ممنونم  sample_form  خیلی قشنگ کار میکنه 
و کد رو بررسی کردم 

مشکلم تو این بخش بود
```

        bank_obj = bank.ready()
        bank.redirect_gateway()
```

من از اینو زده بودم ```

        bank_obj = bank.ready()
        bank.get_gateway_payment_url()
```
چون باید رسپانس api بدم 

الان اینکارو کردم مشکل حل شد

```
        bank_obj = bank.ready()
        bank.redirect_gateway()
        bank.get_gateway_payment_url()
```
