### ISSUE TITLE
مشکل دیتابیس

### ISSUE THREAD

**Issue by AMB82** [ali-zahedi/az-iranian-bank-gateways#60]
سلام وقت بخیر
در صورت امکان ارور زیر که توی stackoverflow ثبت شده رو پاسخ بدید
https://stackoverflow.com/questions/75297057/python-banktype-cannot-be-converted-to-a-mysql-type-error-in-django
با تشکر

**Comment by ali-zahedi** [comment]
@AMB82 
لطف کنین ورژن مورد استفاده این پکیج و جنگو رو بفرمایید. 
```pip freeze |grep -i az ```

همینطور لطفا حتما با فعال کردن محیط تست ```IS_SAMPLE_FORM_ENABLE```  و http://127.0.0.1:8000/bankgateways/sample-payment/ 
تست بکنید. 

ممنون میشم نتیجه رو بفرمایید.
