### ISSUE TITLE
سلام خسته نباشید

### ISSUE THREAD

**Issue by miladamini** [ali-zahedi/az-iranian-bank-gateways#62]
من همه کار هارو کردم طبق مستندات و فیلم خودتون پیش رفتم اما 
Reverse for '/callback-gateway/' not found. '/callback-gateway/' is not a valid view function or pattern name.
این ارور رو میکنم و به هر روشی امتحان میکنم باز ارور کالبک دارم چه کار باید بکنم؟

**Comment by ali-zahedi** [comment]
@miladamini سلام و وقت بخیر. 
حتما مطمئن بشید که یو آر ال رو در فایل یو آر ال ست کرده باشید. 
 اگر ست کردید میتونید حالت تست رو در تنظیمات فعال کنید و طبق راهنما جلو برید و درگاه رو تست کنید. 
 اگر باز هم مشکل داشتید اطلاعات بیشتری رو اینجا بزارید. مثل اینکه از چه درگاهی استفاده میکنید. چه ورژنی رو فعال کردید، فایل یو آر ال رو اینجا کدهاش و بزارید و تنظیمات بدون رمز های درگاه.

**Comment by miladamini** [comment]
سلام خسته نباشید 
من هنوز نمیتونم به درگاه بانکی وصل بشم و با این ارور مواجه میشم 

وقتی میرم به ادرس go_to_gateway_view این ارور میگم و هنوز درگاه بانکی به نمایش نداده و حتی بک ریکویست نگرفتم تا این ارور رو بده ولی چرا میده نمیدونم

**Comment by miladamini** [comment]
![image](https://user-images.githubusercontent.com/130686922/232736270-b714b32e-8c29-4332-8bef-e4d42a763556.png)
![image](https://user-images.githubusercontent.com/130686922/232736435-7359231c-6217-4b5a-a371-e59fa11382c9.png)
![image](https://user-images.githubusercontent.com/130686922/232736549-d11a22f9-b00a-455e-ba65-33fd9a1ae53f.png)

**Comment by miladamini** [comment]
![image](https://user-images.githubusercontent.com/130686922/232736959-1a2a5b6c-5fe4-4e09-bd91-10ef81d6d7f7.png)
![image](https://user-images.githubusercontent.com/130686922/232737067-810c7edd-679b-4c9e-8845-97e55ad9e432.png)
![image](https://user-images.githubusercontent.com/130686922/232737143-5933c427-ae8d-47c8-99aa-6dc42608e186.png)
![image](https://user-images.githubusercontent.com/130686922/232737255-bf1a43a9-37a2-4bb9-a814-a19c3adb917e.png)
![image](https://user-images.githubusercontent.com/130686922/232737340-aa8c5037-7482-410c-95ae-29663e62b4b1.png)

**Comment by miladamini** [comment]
این کل پروژس 
یک پروژه خیلی سادس ک فقط طبق ویدیو یک اپ ساختم و تام
میخوام رو پروژ اصلیم رانش کنم اما این به این ارور برخوردم

**Comment by ali-zahedi** [comment]
محبت کنید و یه فیلم یا گیف بگیرید. به فرم نمونه برید که آدرسش توی مستندات هست. فرم رو پر کنید و دکمه ارسال و بزنید. 
دیباگ مود جنگو رو هم فعال کنید. 
فیلم و بفرستید اطلاعات بیشتری دستم میاد. متشکرم.

**Comment by miladamini** [comment]
[2023-04-18 14-32-08.zip](https://github.com/ali-zahedi/az-iranian-bank-gateways/files/11260649/2023-04-18.14-32-08.zip)

**Comment by miladamini** [comment]
بفرمایید فایل ویدیویی داخل فایل زیپه 
منتظر جوابتون هستم

**Comment by ali-zahedi** [comment]
![image](https://user-images.githubusercontent.com/5299864/232754928-8ef39e6a-6a07-4f36-85d1-ba08f854b6f0.jpeg)

چیزی که از عکس مشخص هست اعتبار سنجیتون مشکل داره. یعنی کلید یا ای پی. خیلی وقت ها درگاه ها باید ای پی استاتیک بدید به عنوان مثال. 

میتونید حالت سندباکس و فعال کنید که خیلی از درگاه ها یک سری از قوانین مثل ای پی و اینها رو غیر فعال میکنن و میتونید تست بگیرید. 
بنظر نمیاد اینطرف مشکلی باشه چون نمونه کد سمپل درست داره کار میکنه.

**Comment by miladamini** [comment]
یعنی الان مشکل از درگاه بانکی منه 
خیلی ممنون بابت کمکتون تشکر
