### ISSUE TITLE
ارور  متصل شدن

### ISSUE THREAD

**Issue by miladamini** [ali-zahedi/az-iranian-bank-gateways#64]
سلام خسته نباشید من همه کار هارو طبق چیزی ک گفتین انجام دادم 
وتو حالت دیباگ کار میکنه و به درگاه متصل میشه و گذینه موفق بودن و ناموفق بودن برام میاره
اما وقتی از حالت دیباگ خارج میک
![image](https://user-images.githubusercontent.com/130686922/236696698-0d6bfda1-d2aa-47e2-b3fc-c704f5bbe58e.png)
![image](https://user-images.githubusercontent.com/130686922/236696725-8a7a70e6-6ee4-4ac5-977c-cabefbd9085f.png)
با این ارور مواجه میشم

**Comment by miladamini** [comment]
و اینم بگم ک فقط از درگاه زرین پال استفاده میکنم

**Comment by miladamini** [comment]
![image](https://user-images.githubusercontent.com/130686922/236696888-02f62f8f-161e-4a86-a015-766aa725bb5e.png)

**Comment by ali-zahedi** [comment]
سلام وقت بخیر. 
اگر در حالت دیباگ درست کار میکنه پس این سمت مشکلی نیست و باید از سمت درگاه (زرین پال) مشکل و پیگیری کنید.  شرایط و ضوابطی که دارن رو انجام بدید (به عنوان مثال ای پی(ip) هاتون رو معرفی کنید فرم هاشون رو پر کنید و ....). در نهایت با پشتیبانیشون باید پیگیری کنید. تاکید میکنم اگر حالت دیباگ مود کار میکنه و به درگاه میرید، اینطرف مشکلی نیست و ارتباط با درگاه از طرف درگاه رد میشه. 

#62 
https://github.com/ali-zahedi/az-iranian-bank-gateways/issues/62#issuecomment-1512867361

**Comment by miladamini** [comment]
[1.zip](https://github.com/ali-zahedi/az-iranian-bank-gateways/files/11420040/1.zip)

**Comment by miladamini** [comment]
لطفا مشهاده کنید
این ایا مشکل از زرین پاله ؟
اخه من همه چیز زرین پال رو به درستی اماده کردم و درگاه برام فعال شده است و محدودیت اپی براش تعیین نکرده ام

**Comment by ali-zahedi** [comment]
اگر در حالت سندباکس کار میکنه و وقتی از سندباکس خارج میکنید کار نمیکنه مشکل از سمت تنظیمات درگاهتون هست که درخواست پرداخت رد میشه، با پشتیبانی درگاهتون باید در ارتباط باشید.  اگر کد یا هر چیزی رو تغییر میدید و بعد کار نمیکنه مشکل رو احتمالا در **کد خودتون** باید جستجو کنید. در هر صورت اینجا بنظر نمیاد مشکلی وجود داشته باشه.

**Comment by miladamini** [comment]
لطفا مشهاده کنید
این ایا مشکل از زرین پاله ؟
اخه من همه چیز زرین پال رو به درستی اماده کردم و درگاه برام فعال شده است و محدودیت اپی براش تعیین نکرده ام

**Comment by miladamini** [comment]
خیلی ممنون بابت پاسخگوییتون حتما الان به پشتیبانی مراجعه میکنم

**Comment by miladamini** [comment]
![image](https://user-images.githubusercontent.com/130686922/236865809-cb8f57e6-14df-405f-a347-66327a7e5d1b.png)

**Comment by miladamini** [comment]
https://www.zarinpal.com/docs/paymentGateway/

**Comment by ali-zahedi** [comment]
@miladamini من با درگاه زرین پال چک کردم و مشکلی وجود ندداشت.
