### ISSUE TITLE
امکان ارث‌بری از مدل بانک

### ISSUE THREAD

**Issue by mh-alahdadian** [ali-zahedi/az-iranian-bank-gateways#69]
با سلام و خسته نباشید 
لایبری خیلی عالی ای نوشتید و بسیار ازتون ممنونیم 

من میخواستم که ابجکت های پرداخت ام به سبد خرید و یوزر ام متصل باشه و ForeignKey داشته باشه ولی کد رو که بررسی کردم دیدم در حال حاضر امکان پذیر نیست 
میخواستم درخواست کنم اگر امکان اش هست کد مربوط به BankFactory , Bank رو به گونه ای تغیر بدیم که بشه مدل کاستوم شده نوشت و به `factory.create()` پاس داد تا در زمان `factory.ready()` از اون مدل استفاده کنه و بتونیم دیتاهای دیگه ای که نیاز داریم وابسته به پروژه رو توی مدل پرداخت نگه داریم 

باتشکر

**Comment by ali-zahedi** [comment]
@mh-alahdadian سلام و عرض ادب. 
میشه کلاسی رو نوشت و در تنظیمات تعیینش کرد که به عنوان کلاس جایگزین استفاده بشه. 
ولی در حال حاضر میتونین به صورت کلید خارجی مدلی که مد نظرتون هست رو بهش متصل کنید.
