### ISSUE TITLE
The Python package contains changes in the model that do not exist in the migrations.

### ISSUE THREAD

**Issue by ravexina** [ali-zahedi/az-iranian-bank-gateways#70]
سلام و وقت بخیر

ظاهرا در مدل‌ تغییراتی اعمال شده و پس از اعمال این تغییرات migration تولید نشده. در نتیجه در محیط توسعه زمانی که کاربر برای تولید migrationهای Applicationهای موجود در پروژه از دستور makemigrations استفاده کند، برای این تغییرات جدید در بسته az-iranian-bank-gateways فایل migration جدیدی ایجاد شده و پروژه کاربر به این فایل وابسته خواهد شد:

`0005_alter_bank_bank_type_alter_bank_created_at_and_more.py`

حال اگر کاربر قصد داشته باشد در یک محیط جدید عملیات پایگاه‌داده را migrate کرده یا از دستور runserver استفاده نماید، پروژه به یک فایل migration که وجود ندارد وابسته بوده و غیر قابل استفاده خواهد بود.

حتی استفاده از دستور زیر برای تولید فایل migration بسته az-iranian-bank-gateways:

`./manage.py makemigrations azbankgateways`

با خطای عدم وجود فایل: `0005_alter_bank_bank_type_alter_bank_created_at_and_more` مواجه خواهد شد.

برای صحت سنجی این مسئله:

```bash
$ virtualenv venv
$ source venv/bin/activate
$ pip install django
$ pip install az-iranian-bank-gateways
$ django-admin startproject myproject
```

سپس app را به settings.py اضافه کنید.

```
$ ./manage.py makemigrations --dry-run
Migrations for 'azbankgateways':
  /home/username/venv/lib/python3.11/site-packages/azbankgateways/migrations/0005_alter_bank_bank_type_alter_bank_created_at_and_more.py
    - Alter field bank_type on bank
    - Alter field created_at on bank
    - Alter field status on bank
    - Alter field update_at on bank
```

در حال حاضر بنده برای اینکه این مسئله رو به نحوی مدیریت کنم فایل‌های migration که بر روی `0005_alter_bank_bank_type_alter_bank_created_at_and_more` وابسته شده اند را به صورت دستی به این شکل تغییر دادم:

```python
dependencies = [
    ("azbankgateways", "__first__"),
]
```

**Comment by pedram-fatahi** [comment]
من هم همین مشکل را دارم منتها در سرور دسترسی برای این تغییرات را ندارم.
