### ISSUE TITLE
هندل نشدن ارور ۲۴ برای درگاه بانک ملت

### ISSUE THREAD

**Issue by zamoosh** [ali-zahedi/az-iranian-bank-gateways#79]
سلام و عرض خسته‌نباشید!
معذرت میخوام آقای زاهدی @ali-zahedi امکانش هست راهنمایی کنید؟ 
ارور با کد ۲۴ برای درگاه پرداخت بانک ملت در پکیج شما پوشش داده نشده.

اطلاعات مربوط به فایل و کد مورد نظرم رو براتون مشخص کردم.

![image](https://github.com/ali-zahedi/az-iranian-bank-gateways/assets/77716607/efe14cf4-fee6-4e00-af4b-4f18d067523f)

**path: /azbankgateways/banks/mellat.py**

hello mr.zahedi @ali-zahedi and thanks for you package!
sir, the response with code **24** is not covered in your **mellat.py** file. can you pleaes help me how to fix this?
best wishes for you...

**version using:** 
az-iranian-bank-gateways==1.9.0

**Comment by mho3en** [comment]
Maybe Your credentials USERNAME and PASSWORD in settings is wrong.
check that or check with another credentials.

**Comment by zamoosh** [comment]
> Maybe Your credentials USERNAME and PASSWORD in settings is wrong. check that or check with another credentials.

Thanks alot @mho3en! I guess too, I'll check if the problem was the credentials, I would close this issue and update the package...

**Comment by zamoosh** [comment]
As we guessed, the error was for credentials...

here is a usefull [link](https://hamyardesign.com/%D8%B4%D8%B1%D8%AD-%D9%83%D8%AF%D9%87%D8%A7%D9%8A-%D9%BE%D8%A7%D8%B3%D8%AE-%D8%A7%D8%B2-%D8%B3%D9%88%DB%8C-%D8%AF%D8%B1%DA%AF%D8%A7%D9%87-%D8%A8%D8%A7%D9%86%DA%A9-%D9%85%D9%84%D8%AA/) for error code of **MELLAT Bank**


I'll close this issus.
