### ISSUE TITLE
مشکل نصب در جنگو ۵

### ISSUE THREAD

**Issue by mohammadhasananisi** [ali-zahedi/az-iranian-bank-gateways#84]
وقتی میخوام ماگریت کنم با این خطا رو به رو میشم

![Screen Shot 2024-03-07 at 10 50 07](https://github.com/ali-zahedi/az-iranian-bank-gateways/assets/47121464/190ea127-b987-486f-8fff-a93f879758c8)

**Comment by ali-zahedi** [comment]
مشکل ترجمه و چند زبانه بودن
#83

**Comment by ali-zahedi** [comment]
#104
